services:
  - type: web
    name: log-receiver
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
